name: proton_session
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/j4qfrost/proton-session-dart.git

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  bcrypt: ^1.1.3
  crypto: ^3.0.3
  dart_pg: ^1.1.5
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
