name: proton_session
description: This is the a partial port of https://github.com/ProtonMail/proton-python-client.git. You can find its license under COPYING.
version: 1.0.1
repository: https://github.com/j4qfrost/proton-session-dart.git

environment:
  sdk: ^3.0.6

dependencies:
  bcrypt: ^1.1.3
  crypto: ^3.0.3
  dart_pg: ^1.1.5
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
